# Generated by Django 4.0.8 on 2022-11-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_tfcuser_phonenumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Subscription plan'},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='date',
            new_name='datetime',
        ),
        migrations.AlterField(
            model_name='tfcuser',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('name', 'fee', 'pay_period')},
        ),
    ]
