# Generated by Django 4.0.8 on 2022-11-18 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='studio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studios.studio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='studio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studios.studio'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='recurringenrollspecificsessiondrop',
            unique_together={('recurring_enroll', 'session_num')},
        ),
    ]
