# Generated by Django 4.0.8 on 2022-12-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0003_alter_amenity_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='capacity',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='studio',
            name='address',
            field=models.CharField(default='Default Address', max_length=200),
        ),
        migrations.AlterField(
            model_name='studio',
            name='phone',
            field=models.CharField(default='111-111-1111', max_length=12),
        ),
        migrations.AlterField(
            model_name='studio',
            name='postal_code',
            field=models.CharField(default='Default Postal Code', max_length=50),
        ),
    ]
